#!/usr/bin/env python3
import argparse
import subprocess

from qubesdb import QubesDB

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Use -k/--key one or more times to read the specified key from QubesDB.  All subsequent arguments will be interpreted as the command to be invoked with those keys set as environment variables.")
    parser.add_argument("-k", "--key", action="append")
    args = parser.parse_known_args()

    env = {}
    try:
        db = QubesDB()
        for key in args[0].key or []:
            value = db.read(f"/vm-config/{key}")
            env[key] = value or ''

        if len(args[1]) > 0:
            cmd = subprocess.Popen(args[1], env=env)
            cmd.wait()

    finally:
        db.close()