"""DraftReply: add column for sending PID

Revision ID: 414627c04463
Revises: d7c8af95bc8e
Create Date: 2022-05-24 20:48:28.581857

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "414627c04463"
down_revision = "d7c8af95bc8e"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("draftreplies", sa.Column("sending_pid", sa.Integer(), nullable=True))


def downgrade():
    # #457: batch_op.drop_column() is necessary instead of the op.drop_column()
    # automatically generated by Alembic.
    with op.batch_alter_table("draftreplies", schema=None) as batch_op:
        batch_op.drop_column("sending_pid")
