"""delete user info

Revision ID: 26abe302fb3a
Revises: 7f682532afa2
Create Date: 2020-09-14 05:38:05.908792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26abe302fb3a'
down_revision = '7f682532afa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_deleted', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('_uuid', sa.String(length=36), nullable=False))
    op.create_unique_constraint(op.f('uq_users__uuid'), 'users', ['_uuid'])
    op.drop_constraint('uq_users_uuid', 'users', type_='unique')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.create_unique_constraint('uq_users_uuid', 'users', ['uuid'])
    op.drop_constraint(op.f('uq_users__uuid'), 'users', type_='unique')
    op.drop_column('users', '_uuid')
    op.drop_column('users', '_deleted')
    # ### end Alembic commands ###
