"""add first_name, last_name, fullname, initials

Revision ID: 36a79ffcfbfb
Revises: fecf1191b6f0
Create Date: 2019-06-28 15:21:50.893256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a79ffcfbfb'
down_revision = 'fecf1191b6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
