"""add account_deletion_scheduled column

Revision ID: b53f419f9fc7
Revises: bd57477f19a2
Create Date: 2021-11-04 13:06:37.201655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53f419f9fc7'
down_revision = 'bd57477f19a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('account_deletion_scheduled', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'account_deletion_scheduled')
    # ### end Alembic commands ###
