"""add deletion_scheduled columns

Revision ID: d5cc24633a16
Revises: bd57477f19a2
Create Date: 2021-11-04 14:09:27.320783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cc24633a16'
down_revision = 'bd57477f19a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('account_deletion_scheduled', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    op.add_column('sources', sa.Column('conversation_deletion_scheduled', sa.Boolean(name='deleted'), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'conversation_deletion_scheduled')
    op.drop_column('sources', 'account_deletion_scheduled')
    # ### end Alembic commands ###
