"""add Reply.state

Revision ID: f394059c0898
Revises: 414627c04463
Create Date: 2023-03-07 17:22:39.406291

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f394059c0898"
down_revision = "414627c04463"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("replies", sa.Column("state", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("replies", "state")
    # ### end Alembic commands ###
