from securedrop_export.exceptions import ExportEnum

class Status(ExportEnum):

    LEGACY_ERROR_FILE_NOT_FOUND = "ERROR_FILE_NOT_FOUND"
    LEGACY_ERROR_EXTRACTION = "ERROR_EXTRACTION"
    LEGACY_ERROR_METADATA_PARSING = "ERROR_METADATA_PARSING"
    LEGACY_ERROR_ARCHIVE_METADATA = "ERROR_ARCHIVE_METADATA"
    LEGACY_ERROR_GENERIC = "ERROR_GENERIC"

    # Legacy USB preflight related
    LEGACY_USB_CONNECTED = "USB_CONNECTED"
    LEGACY_ERROR_USB_CHECK = "ERROR_USB_CHECK"

    # Legacy USB Disk preflight related errors
    LEGACY_USB_ENCRYPTED = "USB_ENCRYPTED"
    LEGACY_USB_ENCRYPTION_NOT_SUPPORTED = "USB_ENCRYPTION_NOT_SUPPORTED"

    # Legacy Disk export errors
    LEGACY_USB_BAD_PASSPHRASE = "USB_BAD_PASSPHRASE"
    LEGACY_ERROR_USB_MOUNT = "ERROR_USB_MOUNT"
    LEGACY_ERROR_USB_WRITE = "ERROR_USB_WRITE"
