# See <https://github.com/QubesOS/qubes-core-qubesdb/blob/main/python/qubesdb.c>,
# generated using stubgen <https://mypy.readthedocs.io/en/stable/stubs.html>
class Error(RuntimeError): ...

class DisconnectedError(Error): ...

class QubesDB:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def read(self, key: str) -> str: ...
