name: Mac Demo Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# Cancel in-progress builds for the same branch except on main
concurrency:
  group: mac-demo-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  mac-demo:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Bootstrap node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24.15.x"

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
          cache: true
          cache_dependency_path: |
            app/pnpm-lock.yaml
          run_install: |
            - cwd: app

      # Keep version in sync with rust-toolchain.toml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@c0e9df88980754dd93e5833b8dcb1b304c1fe173 # 1.96.0

      - name: Build Mac demo DMG
        working-directory: app
        env:
          # Enable code-signing on PRs (off by default)
          CSC_FOR_PULL_REQUEST: true
        run: pnpm build:mac-demo

      - name: Upload DMG artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: mac-demo
          path: app/dist/*.dmg
