name: Nightlies
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main
  pull_request:  # To test changes in this workflow
    paths:
      - '.github/workflows/nightlies.yml'

# Only allow one job to run at a time because we're pushing to git repos;
# the string value doesn't matter, just that it's a fixed string.
concurrency:
  group: "just-one-please-${{ github.ref }}"

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build-debs:
    strategy:
      fail-fast: false
      matrix:
        debian_version:
          - bookworm
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: "freedomofpress/securedrop-builder"
          path: "securedrop-builder"
          lfs: true
      - name: Build packages
        env:
          NIGHTLY: "1"
          DEBIAN_VERSION: ${{ matrix.debian_version }}
          BUILDER: securedrop-builder
        run: |
          git config --global --add safe.directory '*'
          make build-debs
      - uses: actions/upload-artifact@v7
        id: upload
        with:
          name: build-${{ matrix.debian_version }}
          path: build
          if-no-files-found: error

  commit-and-push:
    if: ${{ github.ref == 'refs/heads/main' }} # Skip when testing workflow
    runs-on: ubuntu-latest
    container: debian:bookworm
    needs:
      - build-debs
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes git git-lfs gpg
      # Repeat this for all supported Debian versions
      - name: Download bookworm artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-bookworm
          path: build-bookworm
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: "freedomofpress/securedrop-apt-test"
          path: "securedrop-apt-test"
          lfs: true
          sparse-checkout: workstation/
          sparse-checkout-cone-mode: false
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: "freedomofpress/build-logs"
          path: "build-logs"
      - uses: actions/create-github-app-token@v3.1.1
        id: app-token
        with:
          app-id: ${{ vars.FPF_BRANCH_UPDATER_APP_ID }}
          private-key: ${{ secrets.FPF_BRANCH_UPDATER_APP_PRIVKEY }}
          permission-contents: write
          repositories: |
            build-logs
            securedrop-apt-test
      - name: Prepare buildinfo files
        run: |
          mkdir -p "build-logs/buildinfo/$(date +%Y)"
          cp -v build-*/*.buildinfo "build-logs/buildinfo/$(date +%Y)"
          mkdir -p "build-logs/workstation/bookworm/nightlies"
          cp -v build-bookworm/*.log "build-logs/workstation/bookworm/nightlies/"
      - name: Sign and commit buildinfo files
        uses: freedomofpress/actionslib/act/signed-commit@main
        with:
          files: |
            buildinfo/
            workstation/
          repo-path: build-logs
          message: |
            Publishing build metadata for workstation nightlies

            Via <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          gpg-key: ${{ secrets.FPF_SDCIBOT_GPG_KEY }}
          gpg-identity: ${{ vars.FPF_SDCIBOT_GPG_IDENTITY }}
          gpg-email: ${{ vars.FPF_SDCIBOT_GPG_EMAIL }}
          push: ""
      - name: Push buildinfo files
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          LOGS_REPO: freedomofpress/build-logs
        run: |
          # Sleep before we push so the token will have propagated across GitHub infra
          sleep 5
          git -C build-logs push https://x-access-token:${GH_TOKEN}@github.com/${LOGS_REPO}.git main
      - name: Prepare packages
        run: |
          cp -v build-bookworm/*.deb securedrop-apt-test/workstation/bookworm-nightlies/
      - name: Sign and commit packages
        uses: freedomofpress/actionslib/act/signed-commit@main
        with:
          files: workstation/bookworm-nightlies/
          repo-path: securedrop-apt-test
          message: |
            Automated SecureDrop workstation build

            Via <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          gpg-key: ${{ secrets.FPF_SDCIBOT_GPG_KEY }}
          gpg-identity: ${{ vars.FPF_SDCIBOT_GPG_IDENTITY }}
          gpg-email: ${{ vars.FPF_SDCIBOT_GPG_EMAIL }}
          push: ""
      - name: Push packages
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PKG_REPO: freedomofpress/securedrop-apt-test
        run: |
          git -C securedrop-apt-test push https://x-access-token:${GH_TOKEN}@github.com/${PKG_REPO}.git main
