name: Tests
on:
  - merge_group
  - push
  - pull_request

# Only build for latest push/PR unless it's main or release/
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith( github.ref, 'refs/heads/release/' ) && !startsWith( github.ref, 'refs/heads/gh-readonly-queue/' ) }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  POETRY_VERSION: 2.3.3

jobs:
  # Run `make test` against all components
  component:
    strategy:
      fail-fast: false
      matrix:
        component:
          - export
          - keyring
          - log
          - proxy
        debian_version:
          - trixie
    runs-on: ubuntu-latest
    container: debian:${{ matrix.debian_version }}
    steps:
      - run: |
          apt-get update && apt-get install --yes git make gnupg sudo pipx
          PIPX_HOME=/opt PIPX_BIN_DIR=/usr/local/bin/ pipx install poetry==$POETRY_VERSION
      - name: Setup user
        run: |
          # We want to run tests as a regular user, similar to Qubes VMs
          useradd --create-home --shell /bin/bash user
      - name: Install Rust-specific dependencies
        run: apt-get install --yes rustup build-essential curl libssl-dev pkg-config
        if: ${{ matrix.component == 'proxy' }}
      - name: Cache Rust
        if: ${{ matrix.component == 'proxy' }}
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml', '**/Cargo.lock') }}
          path: |
            ~/.rustup
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
      - name: Initialize Rust toolchain
        if: ${{ matrix.component == 'proxy' }}
        run: rustup show
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.component }}" == "export" ]]; then
            make -C ${{ matrix.component }} ci-install-deps
            sudo -u user poetry config virtualenvs.options.system-site-packages true
          fi
          sudo -u user poetry -C ${{ matrix.component }} install
      - name: Run test
        run: |
          sudo chown -R user:user .
          sudo -u user PATH=$PATH:$HOME/.cargo/bin make -C ${{ matrix.component }} test
